attention_num: 4
augmentation: Normal
backbone: resnet101
batch_size: 3
class_num: null
data_loader: CUB_200_2011
data_root: dataset/
epochs: 200
experience_num: 16
lr: 0.01
lr_decay_epochs: 0
neg_learn: on
fusion_prob: 0.25
lr_decay_rate: 0
mean_pixel: null
model: AttentiveContrative
name: null
pretrained: false
range: 255
std_pixel: null
trainer: APINetTrainer
